### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by poisax** [felixkmh/DuplicateHider#105]
This started happening a _while_ ago but didn't have the time or energy to deal with it at the time, as a result I don't remember if this was caused by something I did or good ole corruption.

I _think_ this is the only relevant information in my logs but lmk if I need to share more:

> 25-08 18:39:59.243|INFO |PlayniteApplication:Application 9.19.0.15427 started
25-08 18:39:59.265|ERROR|PlayniteApplication:Unhandled exception occured.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Database.ItemCollection`1.<>c.<Add>b__56_0(TItem existingItem, String newName) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 305
   at Playnite.Database.ItemCollection`1.<>c__DisplayClass55_0.<Add>b__0(TItem a) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 290
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Playnite.Database.ItemCollection`1.Add(String itemName, Func`3 existingComparer) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 290
   at Playnite.Database.ItemCollection`1.Add(String itemName) in C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:line 305
   at DuplicateHider.DuplicateHiderSettings.get_RevealedTagId() in E:\Programmierung\playnite-dev\DuplicateHider\source\DuplicateHiderSettings.cs:line 111
   at DuplicateHider.DuplicateHiderPlugin.LocalizeTags() in E:\Programmierung\playnite-dev\DuplicateHider\source\DuplicateHiderPlugin.cs:line 444
   at DuplicateHider.DuplicateHiderPlugin.<OnApplicationStarted>d__49.MoveNext() in E:\Programmierung\playnite-dev\DuplicateHider\source\DuplicateHiderPlugin.cs:line 272
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 61
25-08 18:39:59.282|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory

**Comment by felixkmh** [comment]
That's a crash in Playnite itself. I informed its dev and it is going to be fixed there.
