### ISSUE TITLE
[Issue] DuplicateHider not working on Playnite V9

### ISSUE THREAD

**Issue by Hydra-Spectre** [felixkmh/DuplicateHider#46]
I do not know when it stopped working but I remember it working perfectly on Playnite V8 and not working at all in later versions of Playnite V9.

**Comment by Krekot** [comment]
Don't want to create new issue so will post log from playnite:

25-12 11:10:44.901|ERROR|MainMenu:Main menu extension action failed.
System.ArgumentNullException: Wartość nie może być zerowa.
Nazwa parametru: input
   w System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   w DuplicateHider.NumberToRomanFilter.ApplySingle(String& input) w D:\Programmierung\playnite-dev\DuplicateHider\source\Filters\StringFilters.cs:wiersz 133
   w DuplicateHider.IFilter`1.Apply(T& input) w D:\Programmierung\playnite-dev\DuplicateHider\source\Filters\IFilter.cs:wiersz 53
   w DuplicateHider.DuplicateHiderPlugin.GetFilteredName(Game game, IFilter`1 filter) w D:\Programmierung\playnite-dev\DuplicateHider\source\DuplicateHiderPlugin.cs:wiersz 1381
   w DuplicateHider.DuplicateHiderPlugin.BuildIndex(IEnumerable`1 games, IFilter`1 gameFilter, IFilter`1 nameFilter) w D:\Programmierung\playnite-dev\DuplicateHider\source\DuplicateHiderPlugin.cs:wiersz 1216
   w DuplicateHider.DuplicateHiderPlugin.<GetMainMenuItems>b__60_0(MainMenuItemActionArgs context) w D:\Programmierung\playnite-dev\DuplicateHider\source\DuplicateHiderPlugin.cs:wiersz 745
   w Playnite.DesktopApp.Controls.MainMenu.<>c__DisplayClass18_2.<AddExtensionItems>b__1(Object _, RoutedEventArgs __) w C:\projects\playnite\source\Playnite.DesktopApp\Controls\Menus\MainMenu.cs:wiersz 387

**Comment by felixkmh** [comment]
@Krekot that's very odd. This error indicates that a game name is somehow null. Do you have any custom replacement rules set up?

**Comment by Krekot** [comment]
I suppose no. I just installed it today (Playnite) and added few addons (libraries, DH_Night theme). How to check it?

**Comment by felixkmh** [comment]
If you didn't set them up yourself, there won't be any. Are there games in your list with an empty name?

**Comment by Krekot** [comment]
Yes, 13 games from Amazon library.

**Comment by felixkmh** [comment]
This is the cause for the crash. I can fix such that it won't crash in that case. In the meantime you can set the name of those games manually or delete them. Those games not having a name is apparently a bug in the library integration and shouldn't happen anyway.

**Comment by Krekot** [comment]
Thanks a lot. Removing that games fixed this.

**Comment by Hydra-Spectre** [comment]
This is the error that I got with DuplicateHider:
`30-12 12:54:56.030|ERROR|ExtensionFactory:Failed to load plugin: DuplicateHider
Newtonsoft.Json.JsonSerializationException: Unexpected end when reading JSON. Path 'CustomGroups[11]', line 151, position 0.
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Playnite.Common.Serialization.FromJsonStream[T](Stream stream) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 272
   at Playnite.Common.Serialization.FromJsonFile[T](String filePath) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 302
   at Playnite.Common.DataSerializer.FromJsonFile[T](String filePath) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 90
   at Playnite.SDK.Data.Serialization.FromJsonFile[T](String filePath) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 356
   at Playnite.SDK.Plugins.Plugin.LoadPluginSettings[TSettings]() in C:\projects\playnite\source\PlayniteSDK\Plugins\Plugin.cs:line 323
   at DuplicateHider.DuplicateHiderSettings..ctor(DuplicateHiderPlugin plugin) in D:\Programmierung\playnite-dev\DuplicateHider\source\DuplicateHiderSettings.cs:line 301
   at DuplicateHider.DuplicateHiderPlugin..ctor(IPlayniteAPI api) in D:\Programmierung\playnite-dev\DuplicateHider\source\DuplicateHiderPlugin.cs:line 69`

**Comment by felixkmh** [comment]
It would seem that your config.json for DuplicateHider has been corrupted. I don't know how though, probably due to Playnite crashing at some point while writing to it.
You need to locate the ExtensionData folder in your Playnite's config folder. The folder for DuplicateHider should start with 382f8003. In that folder you should find config.json. If you know how to close a json file you can try to fix it. Otherwise you can either upload it and I will try to fix it or you can simply delete it and a new one will be created when Playnite launches. The second option will require you to reconfigure DuplicateHider, including custom groups and replacement rules.
